version: '2'
services:
  web:
    image: dehy/adminer
    container_name: adminer
    environment:
      VIRTUAL_HOST: adminer.dev
    links:
        - "db"
    ports:
      - "80"
  db:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: youshallnotpass!
      MYSQL_USER: dev
      MYSQL_PASSWORD: 123
    ports:
      - 3306:3306
networks:
  default:
    external:
      name: nginx-proxy
